language: ruby
cache: bundler
bundler_args: "--without production"
rvm:
- 2.4.1
services:
- postgresql
script:
- bin/rake db:reset RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  buildpack: ruby
  api_key:
    secure: YWlLhTlLHvwC/Vdw6SF4DLyH1Fx8ZX15b4mCmkvb/ipWmLrgLLjBrrs2GaI/983QunEOBqEr11C8tuhSD16J25JIXzunL5kJp0v+8FLiC3iJBR12Yk8CO4rJDgXEqAsIsjb2qNlsXavIgTkOtJ47G4SZNJWnowePcpaoRp9qgZqaG0Jrh3rV63OrD7+gYvRXypNMiDkXzqTV3pxAVE0o0NOc+cIUBoRcaQ9W0LElsWYDV8UrrTKyyqngBzpyGGqpe1g801pSaG7AHxxIPy261Is0nqHo8z70Xm0AtaCR6KlpFmxhH5VahItWLbUEwyUfIcwXtltLVL0V4gJIsO4Y6f4eBhb+B6XQ8wGYoQfLrisbp4sjL0YzIELod18dY1t8kVmXolKt1WLuuV0rXyAeyUhmHlE7xYL68jEaF/3fvPSv0WBjrU6Fw+tLlZ9P4H4kxZwCUn/HuXqKepeB/cqiTo3io24CJNoWDnn9XHkColt56mRi5w4FC24jePInJ6M4uo2YFOEpQMVLGeS1O5T9Ohmy0sbwWUKhhhGw9ZsMCy6bkAGeP/MtI5FNfkxENj1c5bYRVKMjyVABQCVr69+4L3eWQJBAUhUZzZz9eCINHBnwW2HLEDDbTE3VXXkISCRtEW4okomOWYtMNNgWTRzU7J73THAHAz19fdZj5jCvQVI=
  app:
    master: corkboard-services
  run:
  - rake db:migrate
env:
  test:
    secure: lLCh3yLvy7mEkgDOzHY1fMH2IthgL0JA2l3IlSkYoiqGm4ob6fqVOJrV8t8uxzZcxK+DBzhqETR+IC8SziGQDQ2UdvEBDnLieS2uyWAuSQq86Ws5869opk7U73/h34gUbWW4pnWxiobjrvRsd1X1rdcGxy0qd6XQYsItKHRilyVyPLoog6AHW5XUo5q4HkJTYojGlTSAyC3Lld9gW/fV+VctVYM4MWaY+eS9kidn08dxQLz78d+wbiCov8g87e/d2TCEaorpKlSgyPAFg+1cJyq060DVdqyx/pIxnK2r8lTPuTqWOUOAYeaJTump+xw/kL9HIRcfsP1C60KvhUUFbhB3oldtg9wxIadfgk+fefIIMYYhxcI5+T0cuZPyTo0CadCCZaS/5e4Z0c1e1Ac1z5Y1b34gy79Y+5uml9fU8+XNwfBYDxue99J0Xi+kYeqorp28JHFtT+VSTYXUBSH4AJa6FNkD1PzBWyww3zjxdrMRwsGN6ry2leJr0SD7l2EClevot0i27feCeXAgXtwn0hmbVVhU/h+9vDdYfLKddWWqD7WdHpvJCmk1cFY3UUIdfLhNxNv41TRlzPTBAOqixqlKZTvifdz/pdY+J2P/3A1uQFBLPpFzWfKkx2uCZZyRBhetj8KkCbNsqMrkGkk5Mnna6NDPJUQBxU0DkRjPxOs=
