development:
  adapter: redis
  url: redis://localhost:6379/
  channel_prefix: corkboard_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:af88b05f99b4096ba445d2a56977b9f5@koi.redistogo.com:9061/
  channel_prefix: corkboard_production
